### ISSUE TITLE
dangell7-hooksv3d-standalone doesnt exit in docker ....

### ISSUE THREAD

**Issue by Goochie** [Transia-RnD/hooks-toolkit-ts#11]
I am going through the set up guide ...

https://hooks-toolkit-client.vercel.app/#starting-the-developer-environment

.... and have got to this point ...

xrpld-cli up:standalone 

..... but i get the following error ...

Error response from daemon: pull access denied for gcr.io/thelab-924f3/dangell7-hooksv3d-standalone, repository does not exist or may require 'docker login': denied: Permission denied for "latest" from request "/v2/thelab-924f3/dangell7-hooksv3d-standalone/manifests/latest".

..... when searching for dangell7-hooksv3d-standalone in docker it doesnt seem to exist, any ideas ?

**Comment by dangell7** [comment]
I pushed a new version. I made the containers public at google but I also had some trouble so now they are hosted at docker.

Should be good to go on version 1.0.6 of the `xrpld-cli`

Sorry it took so long for me to respond.
