### ISSUE TITLE
Incorrect HookReturnCode type definition in @transia/xrpl@latest

### ISSUE THREAD

**Issue by 9oelM** [Transia-RnD/hooks-toolkit-ts#25]
Hey @dangell7 hope you had a great week at Apex. 

I've been working on some tests at [hooks-rs](https://github.com/9oelM/hooks-rs) using [Transia-RnD/hooks-toolkit-ts](https://github.com/Transia-RnD/hooks-toolkit-ts) and [Transia-RnD/xrpl.js](https://github.com/Transia-RnD/xrpl.js/tree/%40transia/xrpl%402.7.3-alpha.10), and noticed a few things that could be improved. But for now I'm just only picking on one of them.

`HookReturnCode` is `string`, but the fork at https://github.com/Transia-RnD/xrpl.js/ has a `number` type. But I'm leaving an issue here because the fork doesn't allow submitting an issue and this repo is using that fork anyway.

The location of the type definition: https://github.com/Transia-RnD/xrpl.js/blob/bbfd0ff242f9f4b55b4803886c6d18b10cc9e14f/packages/xrpl/src/models/transactions/metadata.ts#L11

as you can see the type is a `number`. But as you can easily notice from XRPL API calls or inspecting the ledger explorer, it originally is a `string` type.

![image](https://github.com/Transia-RnD/hooks-toolkit-ts/assets/22465806/e1fc6293-31b9-413e-9855-6f72ad089b82)

There are two possible solutions:
1. This can stay as-is, and do `Number(HookReturnCode)` right after the API call is run, because `HookReturnCode` is a `string` originally. This can make sense because HookReturnCode is guaranteed to be a string that contains number although it's a wrapped in a string.
2. Change the type definition to `HookReturnCode: string` and leave the usage to the users.

I know this is quite a simple problem but I guess it's still good to fix it, easy fix.

**Comment by dangell7** [comment]
@9oelM thank you very much for this issue. I will update this today at the office. Yes, everything should match exactly! :) 

You’re welcome to post those other issues as well.
