### ISSUE TITLE
Length prefix for `varString` field

### ISSUE THREAD

**Issue by tequdev** [Transia-RnD/hooks-toolkit-ts#43]
I would like to use BaseModel to represent the key `0000000000000000000000000000000000000000000000000000000000004D43` in the HookState of the number of members of the Xahau Governance Hook.

I have defined it in the following class, but it seems to assume that there is a length prefix for `varString`, so I have to set the maxStringLength of the `spacer` to -1. Also, for `key`, I want to convert `4D43` to two `MC` characters, but the first byte, `4D`, is considered a length prefix.

Is there any way to deal with this?

```ts
class MemberCountStateKeyModel extends BaseModel {
  spacer: VarString;
  key: VarString;

  getMetadata(): Metadata<BaseModel> {
    return [
      {
        field: "spacer",
        type: "varString",
        maxStringLength: 30 - 1
      },
      {
        field: "key1",
        type: "varString",
        maxStringLength: 2
      },
    ];
  }
}
```

It may also be useful to have a field like ``field: 'padding'`` for when dealing with HookState.

**Comment by dangell7** [comment]
On the binary model there already exists a hash256 type. https://hooks-toolkit-client-v2.vercel.app/hook-tools/binary-models#reference

I also just updated the misc utils and there is a padding function in there. Though it may be only one way and we can change that.

**Comment by dangell7** [comment]
```
class Hash256Model extends BaseModel {
  hash: Hash256;

  getMetadata(): Metadata<BaseModel> {
    return [
      {
        field: "hash",
        type: "hash256",
      },
    ];
  }
}

const hashModel: Hash256Model = new Hash256Model(padHexString(convertStringToHex("MC")))
```

**Comment by tequdev** [comment]
I guess the following HookStateKey in evernode can't be processed?

```cpp
// Network configuration <busyness_detect_period(uint32_t)><busyness_detect_average(uint16_t)>.
const uint8_t CONF_NETWORK_CONFIGURATION[32] = {'E', 'V', 'R', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15};
```
